DROP TABLE IF EXISTS venues;
CREATE TABLE venues (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    venue_name     TEXT    NOT NULL,
    location       TEXT    NOT NULL,
    num_tables     INTEGER NOT NULL DEFAULT 1,
    price_per_game TEXT    NOT NULL,
    bathroom_type  TEXT    NOT NULL,
    rating         INTEGER NOT NULL DEFAULT 1 CHECK(rating BETWEEN 0 AND 5),
    notes          TEXT,
    photo_URL      TEXT,
    status         TEXT    NOT NULL DEFAULT 'approved',
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (1, 'The Mule Bar', 'Portland, OR', 1, '$0.50', 'Gendered', 3, 'ATM and Bar for quarters. No hand chalk. Good lighting. Table is level.', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (2, 'Bare Bones', 'Portland, OR', 1, '$0.75', 'Gender-Neutral', 3, 'Sticks and felt in moderate condition. Has hand chalk. ATM & quarter machine.', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (3, 'Belmont Inn', 'Portland, OR', 2, '$0.50', 'Gendered', 4, 'Free days Sun-Tuesday. Sticks and felt in great condition. Has hand chalk. Great lighting. ATM & Quarter machine.', 'img/belmontinn.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (4, 'Ship Ahoy Tavern', 'Portland, OR', 1, '$0.50', 'Gendered', 2, 'Free Day Sunday. Sticks and felt in poor condition. Decent lighting. Hand chalk. ATM.', 'img/shipahoy.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (5, 'Reel M Inn', 'Portland, OR', 1, '$0.00', 'Gendered', 2, 'Sticks in great condition. Felt in mid-condition. Hand chalk. Decent lighting. Individual bathroom stalls.', 'img/reelminn.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (6, 'Clinton Street Pub', 'Portland, OR', 1, '$0.25', 'Gendered', 3, 'Sticks and felt in great condition. Hand chalk. No pool light. Individual bathroom stalls. ATM & Quarter machine', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (7, 'Hungry Tiger', 'Portland, OR', 1, '$1.00', 'Gender-Neutral', 2, 'No hand chalk. Centered pool light. ATM.', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (8, 'Clubhouse Bar & Grill', 'Portland, OR', 1, '$0.75', 'Gendered', 2, 'Individual stalls. Stick and felt in good condition. No hand chalk. Centered great lighting. ATM. Very straight sports bar vibes.', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (9, 'Dublin Pub', 'Beaverton, OR', 3, '$0.00', 'Gendered', 0, 'Stick and felt in awful condition. No hand chalk. Centered mediocre lighting. ATM. Gross bathrooms.', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (10, 'LaVernes', 'Portland, OR', 1, '$0.75', 'Gender-Neutral', 4, 'Sticks and felt in great condition. No hand chalk. ATM.', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (11, 'Crow Bar', 'Portland, OR', 1, '$1.00', 'Gender-Neutral', 3, 'Sticks and felt in great condition. No hand chalk. Centered good lighting.', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (12, 'Thunderbird', 'Portland, OR', 1, '$0.00', 'Gender-Neutral', 0, 'Sticks and felt in awful condition. Missing a ball. hand chalk. Centered poor lighting.', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (13, 'Bear Paw Inn', 'Portland, OR', 2, 'By the Hour', 'Gendered', 3, 'Sticks and felt in decent condition. hand chalk. Centered good lighting. ATM & quarter machine.', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (14, 'Roadside Attraction', 'Portland, OR', 1, '$0.00', 'Gendered', 1, 'Individual stalls. stick and felt in poor condition. Hand chalk. centered decent lighting. ATM.', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (15, 'Joes Cellar', 'Portland, OR', 3, '$0.00', 'Gendered', 3, 'Stick and felt in good condition. Hand chalk. centered good lighting. ATM & quarter machine.', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (16, 'Panther Club PDX', 'Portland, OR', 2, '$0.75', 'Gender-Neutral', 4, 'Stick and felt in great condition. no hand chalk. table is level. ATM & quarters at bar.', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (17, 'Sit Tite', 'Portland, OR', 1, '$1.00', 'Gender-Neutral', 4, 'Sticks & felt great condition. No hand chalk. Great lighting. Table is level. ATM & Quarter machine.', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (18, 'The Perch', 'Portland, OR', 1, '$1.00', 'Gendered', 1, 'Not too shabby. Karaoke nights are especially busy (small bar). Decent lighting. Chalk provided. No ATM or quarter machine.', 'img/barebones.png', 'approved');
INSERT OR IGNORE INTO venues (id, venue_name, location, num_tables, price_per_game, bathroom_type, rating, notes, photo_url, status) VALUES (19, 'Slim''s', 'Portland, OR', 1, '$1.00', 'Gendered', 2, 'Decent lighting. Sticks and felt are in decent condition. ATM.', 'img/uploads/bbc4620a9db5450bae3ab410ecbbc15d.png', 'approved');
